### ISSUE TITLE
Proxy Server printing exception when zero nodes registered in ZK

### ISSUE THREAD

**Issue by thilinamb** [Project-Sustain/synopsis-dht#22]
```
2020-04-20 15:41:18 ERROR MembershipTracker:108 - Error fetching child nodes.
org.apache.zookeeper.KeeperException$NoNodeException: KeeperErrorCode = NoNode for /sustain_dht_nodes
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:111)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:51)
	at sustain.synopsis.dht.zk.MembershipTracker.processResult(MembershipTracker.java:108)
	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:581)
	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:495)
```

**Comment by thilinamb** [comment]
This only happens when a proxy is started before any DHT nodes with a fresh ZK ensemble.
